### ISSUE TITLE
"Login" page / Authentication

### ISSUE THREAD

**Issue by stefnotch** [sueszli/matchy#1]
- [x] Sign up/in with magic link
- [x] One single role for the participants and organizers
- [x] `auth.ts` store (see `counter.ts` for a very simplistic example I guess)
- [x] [Routes](https://github.com/sueszli/matchy/blob/main/frontend/src/router/index.ts) need to know if the user has to be logged in to see that page

**Comment by sueszli** [comment]
Validation of user input for login page: pressing send button before entering an email shows up a success and error message at once

**Comment by stefnotch** [comment]
@sueszli I think that should be fixed now. Please confirm and if yes, close this issue :)

**Comment by sueszli** [comment]
@stefnotch Yess! Awesome - thanks
