### ISSUE TITLE
"Edit Profile" page (= also registration page)

### ISSUE THREAD

**Issue by stefnotch** [sueszli/matchy#2]
- [x] After signing up, we should ask users for what name to use on the app
- [x] We should also ask them for additional info
- [x] The name should be change-able (profile edit page)
- [x] The contact info should be change-able (profile edit page)
- [x] The account should be delete-able

**Comment by sueszli** [comment]
Awesome job guys!
Just tested this feature thoroughly. @MJDeligan you did a great job. Thank you so much man.
