### ISSUE TITLE
Supabase: Create tables, policies, constraints, triggers, edge functions and RPCs in Supabase

### ISSUE THREAD

**Issue by sueszli** [sueszli/matchy#22]
## Make tables
- [x] Create tables in backend based on DB schema design
- [x] Add descriptions for all tables
- [x] Write non cyclic policies

<br>

## Create SMTP function, webhook
- [x] Create SMTP account
- [x] Create function that notifies the user via mail
This function will be used when
      1. matches get published
      2. events get canceled
- [x] Create the hook that calls the function
- [x] Edit the function to notify users on changes in the `notifications` table

<br>

## Create delayed function call (CRON job)
- [x] Matches should be determined after a delay, then the user should be notified

<br>

## Write functions for convenience
- [x] Create trigger that creates a profile on the creation of a user
- [x] Convenience RPC for creation of events that lets you pass arguments for the creation of groups 
- [x] Inject user ID with trigger when creating votes

<br>

## Update docs, make backups
- [ ] Upload swagger API docs as html to "api"/"backend" directory in source directory (will be used in github pages documentation later) 
- [ ] Upload API docs from Supabase
- [ ] Upload copies of *all* SQL queries made in the backend

**Comment by MJDeligan** [comment]
For the api docs we could use [swagger-ui](https://github.com/swagger-api/swagger-ui/releases/tag/v4.14.0) which is just plain html/css/js.

**Comment by stefnotch** [comment]
@MJDeligan Which things do we have to document?
As in, Supabase comes with its own client for most things. And said client already abstracts most of the REST API things away, thus potentially making Swagger a less ideal choice. Not sure. 🤔

**Comment by MJDeligan** [comment]
@stefnotch The endpoints are less important but I find easier to refer to the visualized Schemas for the types especially when working with multiple types. It also lists the RPCs, which the Supabase type-gen does not for some reason.

**Comment by sueszli** [comment]
@MJDeligan Good idea!

This way we don't have to give everyone access to the supabase backend and can make the development more safe.

**Comment by sueszli** [comment]
I'm closing this issue because we split the missing tasks it up into the issues:
- making user input validations in the backend (https://github.com/sueszli/matchy/issues/30)
- backing everything up on github (https://github.com/sueszli/matchy/issues/28)
