### ISSUE TITLE
Integrate toasts

### ISSUE THREAD

**Issue by stefnotch** [sueszli/matchy#40]
Having toasts that are usable everywhere with minimal, and a dedicated utility `showErrorToast(error)` function would be useful. The `showErrorToast` function would replace the `console.log()` in every `try catch` block.

**Comment by sueszli** [comment]
In the previous iteration we used ngx-toastr: https://github.com/sueszli/dateWatch/blob/main/frontend/src/styles.scss

**Comment by sueszli** [comment]
Here are a couple of neat options i found for vue 3:
- https://github.com/Maronato/vue-toastification
- https://github.com/MeForma/vue-toaster
- https://github.com/dafcoe/vue-notification
- https://github.com/szboynono/mosha-vue-toastify

**Comment by sueszli** [comment]
Done!
