### ISSUE TITLE
Fix EditEvent using computed in v-model

### ISSUE THREAD

**Issue by stefnotch** [sueszli/matchy#57]
https://github.com/sueszli/matchy/blob/23d766d1a5bc187adb105759f40ce1ce0130dd3d/frontend/src/components/EditEvent.vue#L44 uses a computed

**Comment by MJDeligan** [comment]
I just had a look at it and fixed the inputs, but I don't see why that would be an issue, since those are not the real inputs anyways, they just display the selected value. I changed the v-model to :model-value though since it is readonly anyways.

**Comment by stefnotch** [comment]
Yeah, that's my main issue. If the component were to ever attempt to change the value, Vue would probably complain.
So yeah, changing it to :model-value is a lovely fix, thank you 👍
